# Generated by Django 4.2.7 on 2023-11-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_code', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_Cover_File', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_Level', models.IntegerField(blank=True, null=True)),
                ('Course_Info', models.CharField(blank=True, max_length=100, null=True)),
                ('Use_Flag', models.BooleanField(blank=True, null=True)),
                ('Register_DateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('Updated_DateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('Register_Agent', models.CharField(blank=True, max_length=100, null=True)),
                ('Course_Provider', models.CharField(blank=True, max_length=100, null=True)),
                ('Syllabus', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('Center_Code', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
